### ISSUE TITLE
Card object 타입 미지원

### ISSUE THREAD

**Issue by bhyoo99** [portone-io/react-native-sdk#14]
### 이슈 개요
request 내 payMethod가 "CARD"일 때 card 객체 추가시 타입 에러가 노출됩니다.

<img width="748" alt="image" src="https://github.com/user-attachments/assets/99125ca3-ac60-4ab6-8af7-67957e719264">

### 이슈 재현
https://github.com/portone-io/portone-sample/blob/main/react-native-expo/App.tsx
해당 링크 예제 -> request props내 card 오브젝트 추가 시도

**Comment by kiwiyou** [comment]
안녕하세요, 해당 버전 패치를 반영한 0.3.4 버전을 배포하였습니다. 버그를 제보해 주셔서 감사합니다.
